"""
图形化配置向导模块
提供GUI界面引导用户配置环境
"""
import os
import gradio as gr
from typing import Dict, Any, Optional


# 推荐模型列表
OLLAMA_EMBEDDING_MODELS = [
    ("nomic-embed-text", "平衡性能和质量 (推荐)"),
    ("mxbai-embed-large", "更高质量"),
    ("all-minilm", "轻量级"),
    ("snowflake-arctic-embed", "高质量多语言"),
]

OLLAMA_LLM_MODELS = [
    ("qwen2.5:7b", "中文友好 (推荐)"),
    ("llama3.1:8b", "通用性强"),
    ("mistral:7b", "效率高"),
    ("qwen2.5:14b", "更高质量"),
    ("deepseek-coder:6.7b", "代码能力强"),
]

OPENAI_EMBEDDING_MODELS = [
    ("text-embedding-3-small", "性价比高 (推荐)"),
    ("text-embedding-3-large", "更高质量"),
    ("text-embedding-ada-002", "稳定版本"),
]

OPENAI_LLM_MODELS = [
    ("gpt-4o-mini", "性价比高 (推荐)"),
    ("gpt-4o", "更强能力"),
    ("gpt-4-turbo", "稳定版本"),
    ("gpt-3.5-turbo", "经济实惠"),
]

OPENAI_COMPATIBLE_APIS = [
    ("https://api.openai.com/v1", "OpenAI 官方"),
    ("https://api.deepseek.com/v1", "DeepSeek"),
    ("https://open.bigmodel.cn/api/paas/v4", "智谱 GLM"),
    ("https://api.moonshot.cn/v1", "Moonshot Kimi"),
    ("custom", "自定义地址"),
]


class ConfigWizard:
    """配置向导"""
    
    def __init__(self, config_dir: str = "."):
        self.config_dir = config_dir
        self.env_path = os.path.join(config_dir, ".env")
    
    def load_current_config(self) -> Dict[str, str]:
        """加载当前配置"""
        config = {}
        if os.path.exists(self.env_path):
            with open(self.env_path, 'r', encoding='utf-8') as f:
                for line in f:
                    line = line.strip()
                    if line and not line.startswith('#') and '=' in line:
                        key, value = line.split('=', 1)
                        config[key.strip()] = value.strip()
        return config
    
    def save_config(self, config: Dict[str, str]) -> str:
        """保存配置"""
        try:
            with open(self.env_path, 'w', encoding='utf-8') as f:
                f.write("# Dialogue Summarizer Configuration\n")
                f.write("# Generated by Config Wizard\n\n")
                
                f.write("# ============ Backend Selection ============\n")
                f.write(f"DIALOGUE_BACKEND={config.get('backend', 'ollama')}\n\n")
                
                f.write("# ============ Ollama Settings ============\n")
                f.write(f"OLLAMA_BASE_URL={config.get('ollama_base_url', 'http://localhost:11434')}\n")
                f.write(f"OLLAMA_EMBEDDING_MODEL={config.get('ollama_embedding_model', 'nomic-embed-text')}\n")
                f.write(f"OLLAMA_LLM_MODEL={config.get('ollama_llm_model', 'qwen2.5:7b')}\n\n")
                
                f.write("# ============ OpenAI API Settings ============\n")
                f.write(f"OPENAI_API_KEY={config.get('openai_api_key', '')}\n")
                f.write(f"OPENAI_BASE_URL={config.get('openai_base_url', 'https://api.openai.com/v1')}\n")
                f.write(f"OPENAI_EMBEDDING_MODEL={config.get('openai_embedding_model', 'text-embedding-3-small')}\n")
                f.write(f"OPENAI_LLM_MODEL={config.get('openai_llm_model', 'gpt-4o-mini')}\n\n")
                
                f.write("# ============ Vector Database Settings ============\n")
                f.write(f"VECTORDB_TYPE={config.get('vectordb_type', 'chroma')}\n")
            
            return f"✅ 配置已保存到: {self.env_path}"
        except Exception as e:
            return f"❌ 保存失败: {str(e)}"
    
    def test_ollama_connection(self, base_url: str) -> str:
        """测试Ollama连接"""
        try:
            import requests
            response = requests.get(f"{base_url.rstrip('/')}/api/tags", timeout=5)
            if response.status_code == 200:
                models = response.json().get('models', [])
                model_names = [m.get('name', '') for m in models]
                if model_names:
                    return f"✅ 连接成功！已安装模型:\n" + "\n".join(f"  • {m}" for m in model_names[:10])
                return "✅ 连接成功！暂无已安装模型，请使用 ollama pull 安装模型"
            return f"⚠️ 服务器响应异常: {response.status_code}"
        except requests.exceptions.ConnectionError:
            return "❌ 无法连接到Ollama服务，请确保Ollama正在运行"
        except Exception as e:
            return f"❌ 连接失败: {str(e)}"
    
    def test_openai_connection(self, api_key: str, base_url: str) -> str:
        """测试OpenAI API连接"""
        if not api_key:
            return "⚠️ 请输入API Key"
        
        try:
            import requests
            headers = {
                "Authorization": f"Bearer {api_key}",
                "Content-Type": "application/json"
            }
            url = f"{base_url.rstrip('/')}/models"
            response = requests.get(url, headers=headers, timeout=10)
            
            if response.status_code == 200:
                return "✅ API连接成功！"
            elif response.status_code == 401:
                return "❌ API Key无效"
            else:
                return f"⚠️ 服务器响应: {response.status_code}"
        except Exception as e:
            return f"❌ 连接失败: {str(e)}"


def create_config_wizard_ui():
    """创建配置向导UI"""
    wizard = ConfigWizard()
    current_config = wizard.load_current_config()
    
    with gr.Blocks(title="配置向导", theme=gr.themes.Soft()) as demo:
        gr.Markdown("# ⚙️ 配置向导")
        gr.Markdown("通过图形界面配置Dialogue Summarizer系统")
        
        # 当前状态
        with gr.Row():
            config_status = gr.Textbox(
                label="当前状态",
                value="检测到配置文件" if current_config else "未检测到配置文件，将创建新配置",
                interactive=False
            )
        
        # 后端选择
        gr.Markdown("## 1️⃣ 选择后端类型")
        with gr.Row():
            backend = gr.Radio(
                choices=[("🏠 Ollama (本地运行)", "ollama"), ("☁️ OpenAI API (云端服务)", "openai")],
                value=current_config.get("DIALOGUE_BACKEND", "ollama"),
                label="后端类型",
                info="选择使用本地Ollama还是云端OpenAI API"
            )
        
        # Ollama配置
        gr.Markdown("## 2️⃣ Ollama 配置")
        with gr.Group() as ollama_group:
            gr.Markdown("本地模型配置 (仅在选择Ollama后端时生效)")
            
            with gr.Row():
                ollama_base_url = gr.Textbox(
                    label="Ollama 服务地址",
                    value=current_config.get("OLLAMA_BASE_URL", "http://localhost:11434"),
                    info="默认地址，通常无需修改"
                )
                ollama_test_btn = gr.Button("🔗 测试连接", variant="secondary")
            
            ollama_test_result = gr.Textbox(label="连接测试结果", interactive=False)
            
            with gr.Row():
                ollama_embedding = gr.Dropdown(
                    choices=[m[0] for m in OLLAMA_EMBEDDING_MODELS],
                    value=current_config.get("OLLAMA_EMBEDDING_MODEL", "nomic-embed-text"),
                    label="Embedding 模型",
                    info="用于将文本转换为向量"
                )
                ollama_llm = gr.Dropdown(
                    choices=[m[0] for m in OLLAMA_LLM_MODELS],
                    value=current_config.get("OLLAMA_LLM_MODEL", "qwen2.5:7b"),
                    label="LLM 模型",
                    info="用于生成总结"
                )
            
            with gr.Accordion("📖 模型说明", open=False):
                gr.Markdown("""
**Embedding模型:**
- `nomic-embed-text`: 平衡性能和质量，推荐日常使用
- `mxbai-embed-large`: 更高质量，适合精确检索
- `all-minilm`: 轻量级，适合资源受限环境

**LLM模型:**
- `qwen2.5:7b`: 中文友好，推荐中文用户
- `llama3.1:8b`: 通用性强，多语言支持好
- `mistral:7b`: 效率高，响应速度快

安装命令: `ollama pull <模型名>`
                """)
        
        # OpenAI配置
        gr.Markdown("## 3️⃣ OpenAI API 配置")
        with gr.Group() as openai_group:
            gr.Markdown("云端API配置 (仅在选择OpenAI后端时生效)")
            
            openai_api_key = gr.Textbox(
                label="API Key",
                value=current_config.get("OPENAI_API_KEY", ""),
                type="password",
                info="你的API密钥"
            )
            
            with gr.Row():
                openai_base_url = gr.Dropdown(
                    choices=[api[0] for api in OPENAI_COMPATIBLE_APIS],
                    value=current_config.get("OPENAI_BASE_URL", "https://api.openai.com/v1"),
                    label="API 地址",
                    info="支持OpenAI兼容的第三方API"
                )
                openai_custom_url = gr.Textbox(
                    label="自定义地址",
                    value="",
                    visible=False,
                    info="输入自定义API地址"
                )
            
            with gr.Row():
                openai_test_btn = gr.Button("🔗 测试连接", variant="secondary")
            
            openai_test_result = gr.Textbox(label="连接测试结果", interactive=False)
            
            with gr.Row():
                openai_embedding = gr.Dropdown(
                    choices=[m[0] for m in OPENAI_EMBEDDING_MODELS],
                    value=current_config.get("OPENAI_EMBEDDING_MODEL", "text-embedding-3-small"),
                    label="Embedding 模型"
                )
                openai_llm = gr.Dropdown(
                    choices=[m[0] for m in OPENAI_LLM_MODELS],
                    value=current_config.get("OPENAI_LLM_MODEL", "gpt-4o-mini"),
                    label="LLM 模型"
                )
            
            with gr.Accordion("📖 第三方API说明", open=False):
                gr.Markdown("""
支持OpenAI格式的第三方API:

| 服务商 | 特点 | 获取方式 |
|--------|------|----------|
| DeepSeek | 中文友好，性价比高 | https://platform.deepseek.com |
| 智谱 GLM | 国产大模型 | https://open.bigmodel.cn |
| Moonshot | 长文本能力强 | https://platform.moonshot.cn |

选择对应地址后，输入该平台的API Key即可使用。
                """)
        
        # 向量数据库配置
        gr.Markdown("## 4️⃣ 向量数据库")
        with gr.Row():
            vectordb_type = gr.Radio(
                choices=[("ChromaDB (推荐)", "chroma"), ("FAISS (高性能)", "faiss")],
                value=current_config.get("VECTORDB_TYPE", "chroma"),
                label="向量数据库类型",
                info="ChromaDB功能完整，FAISS性能更高"
            )
        
        # 保存按钮
        gr.Markdown("## 5️⃣ 保存配置")
        with gr.Row():
            save_btn = gr.Button("💾 保存配置", variant="primary", scale=2)
            save_result = gr.Textbox(label="保存结果", interactive=False, scale=3)
        
        # 事件处理
        def update_ui(backend_choice):
            """根据后端选择更新UI"""
            return gr.Group(visible=True), gr.Group(visible=True)  # 都显示
        
        backend.change(update_ui, inputs=[backend], outputs=[ollama_group, openai_group])
        
        def test_ollama(url):
            return wizard.test_ollama_connection(url)
        
        ollama_test_btn.click(test_ollama, inputs=[ollama_base_url], outputs=[ollama_test_result])
        
        def test_openai(key, url):
            return wizard.test_openai_connection(key, url)
        
        openai_test_btn.click(test_openai, inputs=[openai_api_key, openai_base_url], outputs=[openai_test_result])
        
        def handle_custom_url(choice):
            return gr.Textbox(visible=(choice == "custom"))
        
        openai_base_url.change(handle_custom_url, inputs=[openai_base_url], outputs=[openai_custom_url])
        
        def save_all(backend_val, ollama_url, ollama_emb, ollama_llm_val, 
                     openai_key, openai_url, openai_emb, openai_llm_val, vectordb_val):
            config = {
                'backend': backend_val,
                'ollama_base_url': ollama_url,
                'ollama_embedding_model': ollama_emb,
                'ollama_llm_model': ollama_llm_val,
                'openai_api_key': openai_key,
                'openai_base_url': openai_url,
                'openai_embedding_model': openai_emb,
                'openai_llm_model': openai_llm_val,
                'vectordb_type': vectordb_val
            }
            return wizard.save_config(config)
        
        save_btn.click(
            save_all,
            inputs=[
                backend, ollama_base_url, ollama_embedding, ollama_llm,
                openai_api_key, openai_base_url, openai_embedding, openai_llm,
                vectordb_type
            ],
            outputs=[save_result]
        )
    
    return demo


def run_config_wizard():
    """运行配置向导"""
    demo = create_config_wizard_ui()
    demo.launch(
        server_name="127.0.0.1",
        server_port=7861,
        share=False,
        show_error=True
    )


if __name__ == "__main__":
    run_config_wizard()
